### ISSUE TITLE
Debug tagged enums & avoid error dropping

### ISSUE THREAD

**Issue by AOx0** [AOx0/adam#20]
Dropping the error values assuming it's a closed channel is a mistake. I suspect it silences serializing errors and other errors non-related to the channel being closed.

https://github.com/AOx0/adam/blob/84fcc0a42c7cf19bccc1868f2524607946da7aea/controller/src/firewall/mod.rs#L69-L92
https://github.com/AOx0/adam/blob/84fcc0a42c7cf19bccc1868f2524607946da7aea/firewall/src/main.rs#L218-L235

- [ ] Properly match for EOF errors
- [ ] Panic on other errors, including serialization/deserialization errors

**Comment by LoloREIN** [comment]
@
